sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

env:
- DOCKER_IMAGE=rsovaje/catalogue:0.1
- DOCKER_PASSWORD=rsovaje123
- DOCKER_USERNAME=rsovaje


script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push "$DOCKER_IMAGE"