apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - image: rsovaje/catalogue:0.1
        name: catalogu
        env:
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://35.240.79.227:8080
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-pass
              key: KUMULUZEE_DATASOURCES0_PASSWORD
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: catalogue